<template>
  <div class="card text-left align-middle">
        <div class="card-header text-left pl-3 pb-2">
        <b class="card-title"> {{ info.email }} </b>
        </div>
    <div class="card-body p-0">
        <img class="card-img-top" :src= "info.imageData" />
    </div>    
    <div id=title class="card-body pl-3 pt-0 pb-2">
      <b>  {{ info.title }} </b>      
    </div>
    <div class="card-body pl-3 pt-0 pb-2">     
      
      {{ info.description }}
    </div>
    <div id="comm" class="card-footer text-muted text-left pl-3">
      {{postedFromNow}}
    </div>

    <div v-if="showcomments">
                <div class="comments list-group">
                    <a
                        :key="c.posted_at"
                        v-for="c in info.comments"
                        class="animate list-group-item list-group-item-action flex-column align-items-start"
                    >
                        <div class="d-flex w-100 justify-content-between">
                            <small>{{ formatTime(c.posted_at) }} by {{ c.email }}</small>
                            <a class="link" @click="removeComment(c.id)">Delete</a>
                        </div>
                        <small>{{ c.comment }}</small>
                    </a>
                </div>

                <form @submit.prevent="postComment" class="form-inline mb-5">
                    <div class="form-group">
                        <input
                            v-model="newComment"
                            type="text"
                            class="form-control"
                            id="imageUrl"
                            placeholder="Any comment?"
                        />
                    </div>
                    <button type="submit" class="btn btn-primary ml-2">Post</button>
                </form>
            </div>

  </div>
</template>

<script>
import moment from "moment";
import store from '@/store.js';
import { Posts } from "@/services"

export default {
  props: ["info", "showcomments"],
  name: "Card",
  data() {
        return {
            store,
            newComment: '',
        };
    },
    methods: {
        async refresh() {
            let post = await Posts.getOne(this.info.id);
            this.info.comments = post.comments;
        },
        formatTime(t) {
            return moment(t.posted_at).fromNow();
        },
        async removeComment(commentId) {
            await Posts.Comments.delete(commentId);
            this.refresh();
        },
        async postComment() {
            if (this.newComment) {
                let postId = this.info.id;
                let comment = {
                    username: this.store.username,
                    comment: this.newComment,
                    postId: postId
                };
                try {
                    await Posts.Comments.add(comment);
                    this.refresh();
                } catch (e) {
                    console.error('Error while posting comment', e);
                } finally {
                    this.newComment = '';
                }
            }
        },
    },
  computed: {
    postedFromNow() {
      return moment(this.info.time).fromNow();
    },
  },
};
</script>

<style lang="scss">

a {
    text-decoration: underline;
}
.card {
  margin-bottom: 70px;
}
#time {
  font-size: xx-small;
}
.comments {
    margin: 20px 0;
}
#comm {
  font-size: small;
}
#title {
  margin-top: 12px;
  font-size: x-large;
  font-family: 'Lucida Bright';
}



/* ----------------------------------------------
  * Generated by Animista on 2020-1-3 19:19:35
  * Licensed under FreeBSD License.
  * See http://animista.net/license for more info. 
  * w: http://animista.net, t: @cssanimista
  * ---------------------------------------------- */
  @-webkit-keyframes fade-in-fwd {
    0% {
        -webkit-transform: translateZ(-80px);
        transform: translateZ(-80px);
        opacity: 0;
    }
    100% {
        -webkit-transform: translateZ(0);
        transform: translateZ(0);
        opacity: 1;
    }
}
@keyframes fade-in-fwd {
    0% {
        -webkit-transform: translateZ(-80px);
        transform: translateZ(-80px);
        opacity: 0;
    }
    100% {
        -webkit-transform: translateZ(0);
        transform: translateZ(0);
        opacity: 1;
    }
}
.animate {
    -webkit-animation: fade-in-fwd 1s cubic-bezier(0.39, 0.575, 0.565, 1) both;
    animation: fade-in-fwd 1s cubic-bezier(0.39, 0.575, 0.565, 1) both;
}

</style>
